### ISSUE TITLE
sitemap is generated at the first start and restart but not while running later

### ISSUE THREAD

**Issue by DarkDau** [Hostwiki/wikijs-sitemap#13]
wikijs-sitemap database connection error.
'Error: Database connection error: Unable to acquire a connection' but when I restart the container it works
` # this is an example from today
wikijs-sitemap    |     at generateSitemap (/wiki/sitemap/generate-sitemap.js:54:15)
wikijs-sitemap    |     at async Task.generateSitemapAndLog [as _execution] (/wiki/sitemap/server.js:40:13)
wikijs-sitemap    | [[2024-04-11T00:00:00.981Z] Error generating sitemap (attempt 14/15):  Error: Database connection error: Unable to acquire a connection
wikijs-sitemap    |     at generateSitemap (/wiki/sitemap/generate-sitemap.js:54:15)
wikijs-sitemap    |     at async Task.generateSitemapAndLog [as _execution] (/wiki/sitemap/server.js:40:13)
wikijs-sitemap    | [[2024-04-11T00:00:00.981Z] Error generating sitemap (attempt 15/15):  Error: Database connection error: Unable to acquire a connection
wikijs-sitemap    |     at generateSitemap (/wiki/sitemap/generate-sitemap.js:54:15)
wikijs-sitemap    |     at async Task.generateSitemapAndLog [as _execution] (/wiki/sitemap/server.js:40:13)
wikijs-sitemap    | Server listening on port 3012
wikijs-sitemap    | [2024-04-11T06:39:53.025Z] sitemap generated successfully.
#################### the whole of 15 attempts
wikijs-sitemap    | [[2024-04-11T00:00:00.981Z] Error generating sitemap (attempt 1/15):  Error: Database connection error: Unable to acquire a connection
wikijs-sitemap    | [[2024-04-11T00:00:00.981Z] Error generating sitemap (attempt 2/15):  Error: Database connection error: Unable to acquire a connection
wikijs-sitemap    | [[2024-04-11T00:00:00.981Z] Error generating sitemap (attempt 3/15):  Error: Database connection error: Unable to acquire a connection
wikijs-sitemap    | [[2024-04-11T00:00:00.981Z] Error generating sitemap (attempt 4/15):  Error: Database connection error: Unable to acquire a connection
wikijs-sitemap    | [[2024-04-11T00:00:00.981Z] Error generating sitemap (attempt 5/15):  Error: Database connection error: Unable to acquire a connection
wikijs-sitemap    | [[2024-04-11T00:00:00.981Z] Error generating sitemap (attempt 6/15):  Error: Database connection error: Unable to acquire a connection
wikijs-sitemap    | [[2024-04-11T00:00:00.981Z] Error generating sitemap (attempt 7/15):  Error: Database connection error: Unable to acquire a connection
wikijs-sitemap    | [[2024-04-11T00:00:00.981Z] Error generating sitemap (attempt 8/15):  Error: Database connection error: Unable to acquire a connection
wikijs-sitemap    | [[2024-04-11T00:00:00.981Z] Error generating sitemap (attempt 9/15):  Error: Database connection error: Unable to acquire a connection
wikijs-sitemap    | [[2024-04-11T00:00:00.981Z] Error generating sitemap (attempt 10/15):  Error: Database connection error: Unable to acquire a connection
wikijs-sitemap    | [[2024-04-11T00:00:00.981Z] Error generating sitemap (attempt 11/15):  Error: Database connection error: Unable to acquire a connection
wikijs-sitemap    | [[2024-04-11T00:00:00.981Z] Error generating sitemap (attempt 12/15):  Error: Database connection error: Unable to acquire a connection
wikijs-sitemap    | [[2024-04-11T00:00:00.981Z] Error generating sitemap (attempt 13/15):  Error: Database connection error: Unable to acquire a connection
wikijs-sitemap    | [[2024-04-11T00:00:00.981Z] Error generating sitemap (attempt 14/15):  Error: Database connection error: Unable to acquire a connection
wikijs-sitemap    | [[2024-04-11T00:00:00.981Z] Error generating sitemap (attempt 15/15):  Error: Database connection error: Unable to acquire a connection
`
**I find it striking that the time stamp to the microsecond is always exactly the same after 15 attempts.**

Are onother users facing this behavior, too?

**Comment by Philipinho** [comment]
Thanks for reporting. I will look into it.

**Comment by RingsGit** [comment]
同样的问题，我使用的 docker 运行的 wikijs-sitemap，postgres16, `docker restart` 可以成功生成，但是无法自动生成。

```
[2025-04-23T06:35:16.821Z] sitemap generated successfully.
Server listening on port 3012
[2025-04-23T06:36:47.403Z] sitemap generated successfully.
[[2025-04-24T00:00:00.996Z] Error generating sitemap (attempt 1/15):  Error: Database connection error: Unable to acquire a connection
    at generateSitemap (/wiki/sitemap/generate-sitemap.js:54:15)
    at async Task.generateSitemapAndLog [as _execution] (/wiki/sitemap/server.js:40:13)
[[2025-04-24T00:00:00.996Z] Error generating sitemap (attempt 2/15):  Error: Database connection error: Unable to acquire 
```
